Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using WorkoutWarriors.Data;
using WorkoutWarriors.Data.Interfaces;
using WorkoutWarriors.Data.Repository;
using WorkoutWarriors.Models;
using WorkoutWarriors.View_Model;

namespace WorkoutWarriors.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardRepsoitory _dashboardRepository;
        private readonly IHttpContextAccessor  _httpContextAccessor;

        public DashboardController(IDashboardRepsoitory dashboardRepsoitory, IHttpContextAccessor httpContextAccessor)
        {
            _dashboardRepository = dashboardRepsoitory;
            _httpContextAccessor = httpContextAccessor;
        }

        private static void MapUserEdit(AppUser user, EditUserDashboardViewModel editVM)
        {
            user.Id = editVM.Id;
            user.MaxBenchPress = editVM.MaxBenchPress;
            user.MaxDeadlift = editVM.MaxDeadLift;
            user.Image = editVM.Image;
            user.City = editVM.City;
            user.State = editVM.State;

        }

        public async Task<IActionResult> Index()
        {
            var userGyms = await _dashboardRepository.GetAllUserGyms();
            var userWorkouts = await _dashboardRepository.GetAllUserWorkouts();

            var dashboardViewModel = new DashboardViewModel()
            {
                Gyms = userGyms,
                Workouts = userWorkouts,

            };
            return View(dashboardViewModel);
        }

        public async Task<IActionResult> EditUserProfile()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var user = await _dashboardRepository.GetUserById(curUserId);

            if (user == null) return View("Error");

            var editUserViewModel = new EditUserDashboardViewModel()
            {
                Id = user.Id,
                MaxBenchPress = user.MaxBenchPress,
                MaxDeadLift = user.MaxDeadlift,
                Image = user.Image,
                City = user.City,
                State = user.State

            };
            return View(editUserViewModel);
        }

        [HttpPost]

        public async Task<IActionResult> EditUserProfile(EditUserDashboardViewModel editVM)
        {

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit profile");
                return View("EditUserProfile", editVM);

            }

            AppUser user = await _dashboardRepository.GetByIdNoTracking(editVM.Id);

            MapUserEdit(user, editVM);

            _dashboardRepository.Update(user);

            return RedirectToAction("Index", "Dashboard");

            
        }
    }
}

Controllers/GymController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WorkoutWarriors.Data;
using WorkoutWarriors.Data.Interfaces;
using WorkoutWarriors.Data.Repository;
using WorkoutWarriors.Models;
using WorkoutWarriors.View_Model;

namespace WorkoutWarriors.Controllers
{
    public class GymController : Controller
    {
       
        private readonly IGymRepository _gymRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public GymController(IGymRepository gymRepository, IHttpContextAccessor httpContextAccessor)
        {
            _gymRepository = gymRepository;
            _httpContextAccessor = httpContextAccessor;


        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Gym> gyms =await _gymRepository.GetAll(); 
            return View(gyms);
        }

        public async Task<IActionResult> Detail(int id)
        {

            Gym gym = await _gymRepository.GetByIdAsync(id);

            return View(gym);

        }

        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();

            var createGymViewModel = new CreateGymViewModel {AppUserId = curUserId };

            return View(createGymViewModel);

        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateGymViewModel gymVM)
        {
            if (ModelState.IsValid)
            {
               
                var gym = new Gym
                {

                    Title = gymVM.Title,
                    Description = gymVM.Description,
                    Image = gymVM.Image,
                    GymType = gymVM.GymType,
                    AppUserId = gymVM.AppUserId,
                    Address = new Address
                    {
                        Street = gymVM.Address.Street,
                        City = gymVM.Address.City,
                        State = gymVM.Address.State

                    }


                };
                _gymRepository.Add(gym);

                return RedirectToAction("Index");
            }

            
            return View("Index");


        }
       
        public async Task<IActionResult> Edit(int id)
        {
            var gym= await _gymRepository.GetByIdAsync(id);
            if (gym == null) return View("Error");
            var gymVM = new EditGymViewModel
            {
                Title = gym.Title,
                Description = gym.Description,
                AddressId = gym.AddressId,
                Address = gym.Address,
                gymType = gym.GymType,
                Image = gym.Image


            };
            return View(gymVM);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditGymViewModel gymVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit Gym");
                return View(gymVM);

            }

            var gym = new Gym
            {
                Id = id,
                Title = gymVM.Title,
                Description = gymVM.Description,
                AddressId = gymVM.AddressId,
                Address = gymVM.Address,
                GymType = gymVM.gymType,
                Image = gymVM.Image


            };

            _gymRepository.Update(gym);

            return RedirectToAction("Index");


        }

        public async Task<IActionResult> Delete(int id)
        {
                
            var gymDetails = await _gymRepository.GetByIdAsync(id);
            if (gymDetails == null) return View("Error");
            return View(gymDetails);

        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteGym(int id)
        {
            var GymDetails = await _gymRepository.GetByIdAsync(id);
            if (GymDetails == null) return View("Error");

            _gymRepository.Delete(GymDetails);
            return RedirectToAction("Index");

        }
    }
}

Controllers/WorkoutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Transactions;
using WorkoutWarriors.Data;
using WorkoutWarriors.Data.Interfaces;
using WorkoutWarriors.Data.Repository;
using WorkoutWarriors.Models;
using WorkoutWarriors.View_Model;

namespace WorkoutWarriors.Controllers
{
    public class WorkoutController : Controller
    {

        private readonly IWorkoutRepository _workoutRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public WorkoutController(IWorkoutRepository workoutRepository, IHttpContextAccessor httpContextAccessor)
        {
            _workoutRepository = workoutRepository;
            _httpContextAccessor = httpContextAccessor;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Workout> workouts = await _workoutRepository.GetAll();
            return View(workouts);
        }

        public async Task<IActionResult> Detail(int id)
        {

            Workout workout = await _workoutRepository.GetByIdAsync(id);

            return View(workout);

        }

        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();

            var createWorkoutViewModel = new CreateWorkoutViewModel { AppUserId = curUserId };

            return View(createWorkoutViewModel);

        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateWorkoutViewModel workoutVM)
        {
            if (ModelState.IsValid)
            {

                var workout = new Workout
                {

                    Title = workoutVM.Title,
                    Description = workoutVM.Description,
                    Image = workoutVM.Image,
                    WorkoutType = workoutVM.WorkoutType,
                    AppUserId = workoutVM.AppUserId,
                    StartTime = workoutVM.StartTime,
                    EntryFee = workoutVM.EntryFee,
                    Twitter = workoutVM.Twitter,
                    Facebook = workoutVM.Facebook,
                    Contact = workoutVM.Contact,


                    Address = new Address
                    {
                        Street = workoutVM.Address.Street,
                        City = workoutVM.Address.City,
                        State = workoutVM.Address.State

                    }


                };

                _workoutRepository.Add(workout);

                return RedirectToAction("Index");

            }

            ModelState.AddModelError("", "Failed to create Workout");
            return View(workoutVM);




        }

        public async Task<IActionResult> Edit(int id)
        {
            var Workout = await _workoutRepository.GetByIdAsync(id);
            if (Workout == null) return View("Error");
            var WorkoutVM = new EditWorkoutViewModel
            {
                Title = Workout.Title,
                Description = Workout.Description,
                AddressId = Workout.AddressId,
                Address = Workout.Address,
                WorkoutType = Workout.WorkoutType,
                Image = Workout.Image,
                EntryFee = Workout.EntryFee,
                Website = Workout.Website,
                Twitter = Workout.Twitter,
                Facebook = Workout.Facebook


            };
            return View(WorkoutVM);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditWorkoutViewModel WorkoutVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit Workout");
                return View(WorkoutVM);

            }

            var Workout = new Workout
            {
                Id = id,
                Title = WorkoutVM.Title,
                Description = WorkoutVM.Description,
                AddressId = WorkoutVM.AddressId,
                Address = WorkoutVM.Address,
                WorkoutType = WorkoutVM.WorkoutType,
                Image = WorkoutVM.Image,
                EntryFee = WorkoutVM.EntryFee,
                Website = WorkoutVM.Website,
                Twitter = WorkoutVM.Twitter,
                Facebook = WorkoutVM.Facebook


            };

            _workoutRepository.Update(Workout);

            return RedirectToAction("Index");


        }

        public async Task<IActionResult> Delete(int id)
        {

            var workoutDetails = await _workoutRepository.GetByIdAsync(id);
            if (workoutDetails == null) return View("Error");
            return View(workoutDetails);

        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteWorkout(int id)
        {
            var workoutDetails = await _workoutRepository.GetByIdAsync(id);
            if (workoutDetails == null) return View("Error");

            _workoutRepository.Delete(workoutDetails);
            return RedirectToAction("Index");

        }
    }
}

Views/Dashboard/EditUserProfile.cshtml
@using WorkoutWarriors.View_Model
@using WorkoutWarriors.Data.Enum

@model EditUserDashboardViewModel

<div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Billing address</h4>
    <form method="post" asp-action="EditUserProfile" enctype="multipart/form-data">
        <input type="hidden" id="Id" name="Id" asp-for="Id" />
          <div class="row g-3">
            <div class="col-sm-6">
                <label asp-for="Image">Image</label>
                <input asp-for="Image" class="form-control" placeholder="Image" value="" required>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

            <div class="col-sm-6">
                <label asp-for="MaxBenchPress">Max Bench Press</label>
                <input asp-for="MaxBenchPress" class="form-control" placeholder="lbs" value="" required>
                <label asp-for="MaxDeadLift">Max Deadlift</label>
                <input asp-for="MaxDeadLift" class="form-control" placeholder="lbs" value="" required />
            </div>


            <div class="mb-3">
                <label asp-for="City">City</label>
                <input asp-for="City" class="form-control" placeholder="1234 Main St">
                <span asp-validation-for="City" class="text-danger"></span>
              
            </div>

            <div class="row">
                <div class="col-md-4 mb-3">
                    <label asp-for="State">State</label>
                    <select asp-for="State" asp-items="@Html.GetEnumSelectList<StateTypes>()" class="custom-select d-block w-100" id="state" required>
                        <option value="">Choose...</option>
                    </select>
                    <div class="invalid-feedback">
                        Please provide a valid state.
                    </div>
                </div>

           
            <button type="submit" class="btn btn-primary btn-sm btn-block">Make Changes</button>
       </form>
  </div>

Views/Dashboard/Index.cshtml
@model WorkoutWarriors.View_Model.DashboardViewModel

<h1 class="display-4 fw-normal">User Dashboard</h1>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Gym" asp-action="Create">Create Gym</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Workout" asp-action="Create">Create Workout</a>
<a type="button" class="btn btn-primary" asp-area="" asp-controller="Dashboard" asp-action="EditUserProfile">Edit User Profile</a>
<div class="album py-5 bg-light">
    <div class="container">
        <h2 class="display-4 fw-normal">Your Workouts</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            @foreach (var item in Model.Workouts)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Workout" asp-action="Detail" asp-route-id="@item.Id"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                                    {
                                        <a asp-controller="Workout" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Workout" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.WorkoutType</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <h2 class="display-4 fw-normal">Your Gyms</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (var item in Model.Gyms)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Gym" asp-action="Detail" asp-route-id="@item.Id"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                                    {
                                        <a asp-controller="Gym" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a asp-controller="Gym" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                    }
                                </div>
                                <small class="text-muted">@item.GymType</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

    </div>
</div>